In [51]:
import pandas as pd

text = ['cat','dogs','love','have','dogs','cats']

data = pd.get_dummies(text)
print(data)
print(data.keys())

     cat   cats   dogs   have   love
0   True  False  False  False  False
1  False  False   True  False  False
2  False  False  False  False   True
3  False  False  False   True  False
4  False  False   True  False  False
5  False   True  False  False  False
Index(['cat', 'cats', 'dogs', 'have', 'love'], dtype='object')


In [68]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
text = ['i love dogs','i hate cats', ' i love cats','i hate dogs']
text = np.reshape(text,(-1,1))
enc = OneHotEncoder()
data = enc.fit_transform(text)
print(data.toarray())
print([x[3:] for x in enc.get_feature_names_out()])

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[' i love cats', 'i hate cats', 'i hate dogs', 'i love dogs']


tokenized sentence

In [71]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
text = [['this','is','good','s'],['but','it','is','fine']]
enc = OneHotEncoder()
data = enc.fit_transform(text)
print(data.toarray())
print([x[3:] for x in enc.get_feature_names_out()])

[[0. 1. 1. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 1. 0.]]
['but', 'this', 'is', 'it', 'good', 'is', 'fine', 's']
