In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('WineQT.csv')

In [5]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
X = df.drop('quality',axis=1)
y=df['quality']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=44)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Data Modeling with SVC**

In [9]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train,y_train)
predictions = svc.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.6200873362445415

# **Hyperparameter Tuning**

In [17]:
param_grid = {
    'C':[0.1,1,10],
    'kernel':['linear','rbf','poly'],
    'gamma':['scale','auto'],
    'degree':[2,3,4]
}

#GridSearchCV
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(svc,param_grid,cv=5)
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'degree': [2, 3, 4],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly']})

In [19]:
grid.best_params_

{'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}

In [18]:
#RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV
random = RandomizedSearchCV(svc,param_grid,cv=5)
random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [0.1, 1, 10], 'degree': [2, 3, 4],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['linear', 'rbf', 'poly']})

In [21]:
random.best_params_

{'kernel': 'rbf', 'gamma': 'scale', 'degree': 4, 'C': 1}

In [42]:
svc_final = SVC(C=1,gamma='scale',kernel='rbf',degree=4)
svc_final.fit(X_train,y_train)


SVC(C=1, degree=4)

In [44]:
predictions = svc_final.predict(X_test)

In [45]:
score = svc_final.score(X_test,y_test)

In [46]:
print(score)

0.6200873362445415


In [47]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(accuracy_score(y_test,predictions))

              precision    recall  f1-score   support

           4       0.00      0.00      0.00         5
           5       0.64      0.80      0.71        88
           6       0.58      0.61      0.59        98
           7       0.75      0.33      0.46        36
           8       0.00      0.00      0.00         2

    accuracy                           0.62       229
   macro avg       0.39      0.35      0.35       229
weighted avg       0.61      0.62      0.60       229

[[ 0  2  3  0  0]
 [ 0 70 17  1  0]
 [ 0 35 60  3  0]
 [ 0  2 22 12  0]
 [ 0  0  2  0  0]]
0.6200873362445415


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
